language: node_js
node_js:
  - '4.0.0'
before_install:
  - npm install -g webpack
install:
  - npm install
  - npm run build
script:
  - npm run test
after_success: 'npm run coverage'
cache:
  directories:
    - node_modules
